### ISSUE TITLE
[Enhancement] Series as a calculation factor

### ISSUE THREAD

**Issue by chocolatechipcats** [SparrowBrain/Playnite.PlayNext#12]
Series would make sense to include as a calculation factor. For example, playing a lot of Half-Life 1 would then recommend Half-Life: Opposing Force or Half-Life 2 if they're unplayed. 

It would be nice if it was able to weight up the 'next' game in the series (perhaps by release year), but I suspect this would be complicated and might not work as expected for some series.

**Comment by SparrowBrain** [comment]
Good point! I'll see if there's a simple way to do series with some 'next' game magic sprinkled in.

**Comment by FedericoSteidl** [comment]
Some ideas that might help:
I suggest using the Sorting Name over Release Date to recognize the next game in the series. If no Sorting Name is set (or the Sorting Name doesn't contain a double-digit number) the fallback would be Release Date.

This would, for example, prevent the plugin from suggesting BioShock Remastered after I just played the original, and suggest BioShock 2 instead (given that the sorting names are "BioShock 01", "BioShock 01 Remastered", "BioShock 02"). This'd also apply to ports of games, since, for example, the release year for "NfS Most Wanted (2012)" is 2020 on steam.

I'd also limit the amount of series suggestions to 1 per series. If I just played tomb raider 1, I wouldn't want all 11 other games suggested at once, just Tomb Raider 2.

**Comment by chocolatechipcats** [comment]
I'm not sure that sorting name would work. Especially if the games are released in  a non-chronological order.

**Comment by Heeervas** [comment]
There's an extension called related games that may possible help here. @SparrowBrain

**Comment by FedericoSteidl** [comment]
> There's an extension called related games that may possible help here. @SparrowBrain

Yes, at the time of writing the original post this extension didn't exist yet, however :)

**Comment by Heeervas** [comment]
> > There's an extension called related games that may possible help here. @SparrowBrain
> 
> Yes, at the time of writing the original post this extension didn't exist yet, however :)

I guessed that when having a read, that's why I commented :) Hopefully it can be added somehow cause it would be amazing

**Comment by SparrowBrain** [comment]
Yeah. It's a great addition. I've started working on it. Sadly, some life
stuff is getting in the way. I hoe to have an update not too far in the
future :).

**Comment by SparrowBrain** [comment]
> There's an extension called related games that may possible help here. @SparrowBrain

Ah and I have installed the related games extension and I have looked at the code if it. So we're thinking alike @Heeervas 😄

**Comment by SparrowBrain** [comment]
@chocolatechipcats @FlyMandi @Heeervas PlayNext v1.5.0 has Series as one of the attributes used in calculations :)

It also gives preference to earlier games in the series, sorted by release date. Optionally, sorting name can be used (not as reliable in my experience).

Thanks for the awesome suggestion!
